version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: ttc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ttc_aalst
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "33060:3306"
    networks:
      - ttcnet
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  webapi:
    build:
      context: ./
      dockerfile: ./src/Ttc.WebApi/Dockerfile
    container_name: ttc-backend
    restart: always
    ports:
      - "7750:8080"
      - "7751:8081"
    networks:
      - ttcnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./upload:/upload
    depends_on:
      - db

volumes:
  mysql-data:

networks:
  ttcnet:
    driver: bridge
