//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttc.DataAccess.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelExportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelExportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ttc.DataAccess.Utilities.ExcelExportResources", typeof(ExcelExportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computernummer.
        /// </summary>
        internal static string CompetitionComputerNumber {
            get {
                return ResourceManager.GetString("CompetitionComputerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string CompetitionIndex {
            get {
                return ResourceManager.GetString("CompetitionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lidnummer.
        /// </summary>
        internal static string CompetitionLidnummer {
            get {
                return ResourceManager.GetString("CompetitionLidnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgnummer.
        /// </summary>
        internal static string CompetitionVolgnummer {
            get {
                return ResourceManager.GetString("CompetitionVolgnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string MatchBlock {
            get {
                return ResourceManager.GetString("MatchBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelle.
        /// </summary>
        internal static string MatchBlockAdminName {
            get {
                return ResourceManager.GetString("MatchBlockAdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapitein.
        /// </summary>
        internal static string MatchBlockCaptainName {
            get {
                return ResourceManager.GetString("MatchBlockCaptainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string MatchDate {
            get {
                return ResourceManager.GetString("MatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dag.
        /// </summary>
        internal static string MatchDay {
            get {
                return ResourceManager.GetString("MatchDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frenoy.
        /// </summary>
        internal static string MatchFrenoyId {
            get {
                return ResourceManager.GetString("MatchFrenoyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuis.
        /// </summary>
        internal static string MatchHome {
            get {
                return ResourceManager.GetString("MatchHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uur.
        /// </summary>
        internal static string MatchHour {
            get {
                return ResourceManager.GetString("MatchHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uit.
        /// </summary>
        internal static string MatchOut {
            get {
                return ResourceManager.GetString("MatchOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string PlayerAddress {
            get {
                return ResourceManager.GetString("PlayerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        internal static string PlayerCity {
            get {
                return ResourceManager.GetString("PlayerCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string PlayerEmail {
            get {
                return ResourceManager.GetString("PlayerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gsm.
        /// </summary>
        internal static string PlayerPhone {
            get {
                return ResourceManager.GetString("PlayerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klassement.
        /// </summary>
        internal static string PlayerRanking {
            get {
                return ResourceManager.GetString("PlayerRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waarde.
        /// </summary>
        internal static string PlayerRankingValue {
            get {
                return ResourceManager.GetString("PlayerRankingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledenlijst.
        /// </summary>
        internal static string SheetAllPlayers {
            get {
                return ResourceManager.GetString("SheetAllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporta.
        /// </summary>
        internal static string SheetSporta {
            get {
                return ResourceManager.GetString("SheetSporta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vttl.
        /// </summary>
        internal static string SheetVttl {
            get {
                return ResourceManager.GetString("SheetVttl", resourceCulture);
            }
        }
    }
}
